services:
  backend:
    build:
      context: ./backend
    environment:
      MAIL_ENABLED: "false"
      APP_SECURITY_ENABLED: ${APP_SECURITY_ENABLED:-true}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_API_URL: ${VITE_BASE_API_URL:-/api/v1}
        VITE_ENABLED_AUTH: ${VITE_ENABLED_AUTH:-true}
    ports:
      - '5173:80'