server:
  port: 8888

spring:
  threads:
    virtual:
      enabled: true
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # Database
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration/schema,classpath:db/migration/seed
    validate-on-migrate: false
    baseline-on-migrate: true

  # Mail
  mail:
    enabled: ${MAIL_ENABLED}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}

# Springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# JWT
app:
  jwtCookieName: ${JWT_COOKIE_NAME}
  jwtRefreshCookieName: ${JWT_COOKIE_REFRESH_NAME}
  jwtSecret: ${JWT_SECRET}
  jwtExpirationsMs: ${JWT_EXPIRATION}
  jwtRefreshExpirationsMs: ${JWT_REFRESH_EXPIRATION}
  frontendUrl: ${FRONTEND_URL}

logging:
  level:
    org.springframework.security: DEBUG
