import i18n from "@/i18n"

export interface FieldError {
  field: string
  message: string
}

export interface ApiError {
  code: string
  message: string
  errors?: FieldError[]
}

const FALLBACK_CODE = 'INTERNAL_ERROR'

const MESSAGES: Record<string, string> = {
  // Auth
  INVALID_PASSWORD: 'Mật khẩu không đúng',
  INVALID_TOKEN: 'Token không hợp lệ',
  TOKEN_EXPIRED: 'Phiên đăng nhập đã hết hạn',
  TOKEN_INVALID_OR_EXPIRED: 'Token không hợp lệ hoặc đã hết hạn',
  TOKEN_ALREADY_USED: 'Token đã được sử dụng',
  REFRESH_TOKEN_NOT_FOUND: 'Không tìm thấy refresh token',
  UNAUTHORIZED: 'Yêu cầu đăng nhập',
  FORBIDDEN: 'Bạn không có quyền thực hiện hành động này',
  USER_NOT_AUTHENTICATED: 'Người dùng chưa được xác thực',
  INVALID_CREDENTIALS: 'Email hoặc mật khẩu không đúng',
  ACCOUNT_NOT_VERIFIED: 'Email tài khoản chưa được xác thực',
  ACCOUNT_NOT_ACTIVE: 'Tài khoản chưa được kích hoạt',
  REQUIRED_LOGIN: 'Vui lòng đăng nhập',
  OTP_RESEND_COOLDOWN: 'Vui lòng đợi 60 giây trước khi yêu cầu mã mới',
  RESET_TOKEN_INVALID: 'Token đặt lại mật khẩu không hợp lệ hoặc đã hết hạn',
  REFRESH_TOKEN_INVALID: 'Refresh token không hợp lệ hoặc đã hết hạn',
  REFRESH_TOKEN_REUSE_DETECTED: 'Phát hiện hành vi tái sử dụng refresh token',
  REFRESH_TOKEN_EXPIRED: 'Refresh token đã hết hạn, vui lòng đăng nhập lại',

  // Common
  VALIDATION_FAILED: 'Dữ liệu không hợp lệ',
  ENDPOINT_NOT_FOUND: 'Không tìm thấy API endpoint',
  INTERNAL_ERROR: 'Đã có lỗi xảy ra, vui lòng thử lại',
  IMAGE_UPLOAD_FAILED: 'Tải ảnh lên thất bại',
  CLOUDINARY_UPLOAD_FAILED: 'Tải file lên Cloudinary thất bại',
  FILE_UPLOAD_DIR_CREATE_FAILED: 'Không thể tạo thư mục tải lên',
  FILE_UPLOAD_SAVE_FAILED: 'Lưu file thất bại',
  EMAIL_SEND_FAILED: 'Gửi email thất bại, vui lòng liên hệ hỗ trợ',
  METHOD_NOT_IMPLEMENTED: 'Tính năng này chưa được triển khai',
  PASSWORD_TOO_SHORT: 'Mật khẩu phải có ít nhất 6 ký tự',
  INVALID_STATE_TRANSITION: 'Trạng thái chuyển đổi không hợp lệ',

  // Catalog
  BRAND_NOT_FOUND: 'Không tìm thấy thương hiệu',
  BRAND_NAME_EXISTS: 'Tên thương hiệu đã tồn tại',
  BRAND_NAME_REQUIRED: 'Tên thương hiệu là bắt buộc',
  CATEGORY_NOT_FOUND: 'Không tìm thấy danh mục',
  CATEGORY_NAME_REQUIRED: 'Tên danh mục là bắt buộc',
  SUPPLIER_NOT_FOUND: 'Không tìm thấy nhà cung cấp',
  SUPPLIER_NAME_REQUIRED: 'Tên nhà cung cấp là bắt buộc',
  PRODUCT_NOT_FOUND: 'Không tìm thấy sản phẩm',
  PRODUCT_NAME_REQUIRED: 'Tên sản phẩm là bắt buộc',
  SKU_REQUIRED: 'Mã SKU là bắt buộc',
  SKU_ALREADY_EXISTS: 'Mã SKU đã tồn tại',
  IMAGE_NOT_FOUND: 'Không tìm thấy ảnh',
  INVALID_UNIT_TRACKING: 'Đơn vị sản phẩm yêu cầu loại theo dõi không hợp lệ',

  // Inventory
  LOCATION_NOT_FOUND: 'Không tìm thấy vị trí',
  LOCATION_CODE_EXISTS: 'Mã vị trí đã tồn tại',
  LOCATION_CODE_REQUIRED: 'Cần nhập mã khu vực, mã kệ và mã ngăn',
  CANNOT_DELETE_LOCATION_WITH_UNITS: 'Không thể xoá vị trí có chứa sản phẩm',
  SOURCE_BIN_EMPTY: 'Vị trí nguồn không có sản phẩm để di chuyển',
  RELOCATE_SAME_BIN: 'Không thể di chuyển đến cùng một vị trí',
  INVALID_QUANTITY: 'Số lượng không hợp lệ',
  CUSTOMER_NOT_FOUND: 'Không tìm thấy khách hàng',
  IMPORT_RECEIPT_NOT_FOUND: 'Không tìm thấy phiếu nhập',
  IMPORT_ITEM_NOT_FOUND: 'Không tìm thấy mục trong phiếu nhập',
  RECEIPT_CODE_EXISTS: 'Mã phiếu đã tồn tại',
  PRODUCT_UNIT_NOT_FOUND: 'Không tìm thấy đơn vị sản phẩm',
  SERIAL_ALREADY_EXISTS: 'Số serial đã tồn tại',
  SERIAL_ALREADY_EXISTS_LIST: 'Các số serial đã tồn tại',
  SERIAL_COUNT_MUST_MATCH: 'Số lượng serial phải khớp với số lượng',
  SERIAL_BLANK: 'Số serial không được để trống',
  IMPORT_ALREADY_COMPLETED: 'Phiếu nhập đã hoàn thành',
  IMPORT_ALREADY_CANCELLED: 'Phiếu nhập đã bị hủy',
  IMPORT_CANNOT_CANCEL_UNITS_EXPORTED: 'Không thể hủy vì một số đơn vị đã được xuất',
  CREATOR_CANNOT_APPROVE: 'Người tạo không thể tự duyệt',
  SERIAL_REQUIRED_FOR_SERIALIZED: 'Số serial là bắt buộc cho sản phẩm theo dõi serial',
  SERIAL_NOT_ALLOWED_FOR_BULK: 'Số serial không được phép cho sản phẩm bulk',
  EXPORT_RECEIPT_NOT_FOUND: 'Không tìm thấy phiếu xuất',
  EXPORT_ALREADY_CANCELLED: 'Phiếu xuất đã bị hủy',
  INSUFFICIENT_STOCK: 'Sản phẩm không đủ tồn kho',
  AT_LEAST_ONE_ITEM_REQUIRED: 'Cần ít nhất một mục',
  EXPORT_REASON_REQUIRED: 'Lý do xuất là bắt buộc',
  CUSTOMER_REQUIRED_FOR_SALE: 'Khách hàng là bắt buộc cho phiếu xuất bán',
  INVALID_EXPORT_REASON: 'Lý do xuất không hợp lệ',
  DISPOSE_ONLY_DAMAGED: 'Chỉ sản phẩm hỏng mới được thanh lý',
  BULK_CANNOT_SELECT_UNITS: 'Không thể chọn đơn vị cụ thể cho sản phẩm bulk',
  UNIT_NOT_BELONG_TO_PRODUCT: 'Đơn vị sản phẩm không thuộc về sản phẩm đã chọn',
  UNIT_NOT_AVAILABLE: 'Đơn vị sản phẩm không khả dụng để xuất',
  SUPPLIER_REQUIRED: 'Nhà cung cấp là bắt buộc',
  ONLY_PENDING_APPROVAL_CAN_APPROVE: 'Chỉ phiếu đang chờ duyệt mới được duyệt',
  ONLY_PENDING_APPROVAL_CAN_CANCEL: 'Chỉ phiếu đang chờ duyệt mới được hủy',
  ONLY_DRAFT_CAN_CONFIRM: 'Chỉ phiếu nhập ở trạng thái nháp mới được xác nhận',
  STOCK_CHECK_NOT_FOUND: 'Không tìm thấy phiếu kiểm kho',
  STOCK_CHECK_ALREADY_APPROVED: 'Phiếu kiểm kho đã được duyệt',
  STOCK_CHECK_ALREADY_REJECTED: 'Phiếu kiểm kho đã bị từ chối',
  STOCK_CHECK_ALREADY_COMPLETED: 'Phiếu kiểm kho đã hoàn thành',
  STOCK_CHECK_ITEMS_REQUIRED: 'Cần ít nhất một mục kiểm kho',
  STOCK_CHECK_MUST_BE_IN_PROGRESS: 'Phiếu kiểm kho phải đang thực hiện để ghi nhận mục',
  STOCK_CHECK_ALREADY_STARTED: 'Phiếu kiểm kho đã được bắt đầu',
  ONLY_COMPLETED_CAN_APPROVE: 'Chỉ phiếu kiểm kho đã hoàn thành mới được duyệt',
  ONLY_COMPLETED_CAN_REJECT: 'Chỉ phiếu kiểm kho đã hoàn thành mới bị từ chối',
  ADJUSTMENT_NOT_FOUND: 'Không tìm thấy phiếu điều chỉnh',
  ADJUSTMENT_TYPE_REQUIRED: 'Loại điều chỉnh là bắt buộc',
  INVALID_ADJUSTMENT_TYPE: 'Loại điều chỉnh không hợp lệ',
  ADJUSTMENT_REASON_REQUIRED: 'Lý do điều chỉnh là bắt buộc',
  ADJUSTMENT_UNIT_REQUIRED: 'Đơn vị sản phẩm là bắt buộc cho điều chỉnh này',
  ADJUSTMENT_PRODUCT_REQUIRED: 'Sản phẩm là bắt buộc cho điều chỉnh tìm thấy không serial',
  ADJUSTMENT_ALREADY_APPROVED: 'Phiếu điều chỉnh đã được duyệt',
  ADJUSTMENT_ALREADY_REJECTED: 'Phiếu điều chỉnh đã bị từ chối',
  ONLY_PENDING_CAN_APPROVE: 'Chỉ phiếu điều chỉnh đang chờ mới được duyệt',
  ONLY_PENDING_CAN_REJECT: 'Chỉ phiếu điều chỉnh đang chờ mới bị từ chối',
  ADJUSTMENT_UNIT_NOT_RESTORABLE: 'Đơn vị sản phẩm không thể khôi phục qua điều chỉnh tìm thấy',
  ADJUSTMENT_PHOTO_REQUIRED_DAMAGED: 'Ảnh là bắt buộc cho điều chỉnh HỎNG',
  ADJUSTMENT_SERIAL_REQUIRED_FOUND: 'Số serial là bắt buộc cho điều chỉnh TÌM THẤY',
  ADJUSTMENT_LOCATION_REQUIRED_FOUND: 'Vị trí là bắt buộc cho điều chỉnh TÌM THẤY',
  REJECTION_REASON_REQUIRED: 'Lý do từ chối là bắt buộc',
  PO_NOT_FOUND: 'Không tìm thấy đơn đặt hàng',
  PO_CODE_EXISTS: 'Mã đơn đặt hàng đã tồn tại',
  PO_ALREADY_CANCELLED: 'Đơn đặt hàng đã bị hủy',
  PO_HAS_COMPLETED_RECEIPTS: 'Không thể hủy đơn đặt hàng đã có phiếu nhập hoàn thành',
  PO_REQUIRED: 'Đơn đặt hàng là bắt buộc',
  EXPORT_ITEM_NOT_FOUND: 'Không tìm thấy mục xuất',
  EXPORT_ACTUAL_QTY_REQUIRED_BULK: 'Số lượng thực tế là bắt buộc cho mục bulk',
  EXPORT_SERIALS_REQUIRED: 'Số serial là bắt buộc cho mục theo dõi serial',
  EXPORT_SERIAL_WRONG_PRODUCT: 'Serial không thuộc về sản phẩm đã chọn',
  EXPORT_SERIAL_NOT_AVAILABLE: 'Serial không khả dụng',
  EXPORT_SERIAL_IN_STOCK_CHECK: 'Serial hiện đang được kiểm kho',
  PRICE_ADJ_NOT_FOUND: 'Không tìm thấy phiếu điều chỉnh giá',
  PRICE_ADJ_ITEM_REQUIRED: 'Mục phiếu nhập là bắt buộc',
  PRICE_ADJ_NEW_PRICE_NEGATIVE: 'Giá mới phải là giá trị không âm',
  PRICE_ADJ_WHOLE_NUMBER: 'Giá mới phải là số nguyên',
  PRICE_ADJ_SAME_PRICE: 'Giá mới trùng với giá hiện tại',
  PRICE_ADJ_REASON_REQUIRED: 'Lý do điều chỉnh giá là bắt buộc',
  PRICE_ADJ_ONLY_PENDING_APPROVE: 'Chỉ phiếu điều chỉnh giá đang chờ mới được duyệt',
  PRICE_ADJ_ONLY_PENDING_REJECT: 'Chỉ phiếu điều chỉnh giá đang chờ mới bị từ chối',
  PRICE_ADJ_DUPLICATE_PENDING: 'Đã có phiếu điều chỉnh giá đang chờ cho mục này',
  PRICE_ADJ_REJECT_REASON_REQUIRED: 'Lý do từ chối là bắt buộc',
  PRICE_ADJ_PRICE_CHANGED: 'Giá sản phẩm đã thay đổi từ khi tạo phiếu điều chỉnh',
  PRICE_ADJ_ONLY_PENDING_CANCEL: 'Chỉ phiếu điều chỉnh giá đang chờ mới được hủy',
  RETURN_RECEIPT_NOT_FOUND: 'Không tìm thấy phiếu trả hàng',
  RETURN_RECEIPT_CODE_EXISTS: 'Mã phiếu trả hàng đã tồn tại',
  RETURN_REASON_REQUIRED: 'Lý do trả hàng là bắt buộc',
  RETURN_ITEMS_REQUIRED: 'Cần ít nhất một mục trả hàng',
  RETURN_EXPORT_REQUIRED: 'Phiếu xuất gốc là bắt buộc',
  RETURN_ALREADY_CANCELLED: 'Phiếu trả hàng đã bị hủy',
  RETURN_ALREADY_COMPLETED: 'Phiếu trả hàng đã hoàn thành',
  RETURN_ONLY_PENDING: 'Chỉ phiếu trả hàng đang chờ mới được xử lý',
  RETURN_CUSTOMER_REQUIRED: 'Khách hàng là bắt buộc',
  RETURN_INVALID_REASON: 'Lý do trả hàng không hợp lệ',
  RETURN_INVALID_CONDITION: 'Tình trạng trả hàng không hợp lệ',
  RETURN_INVALID_ACTION: 'Hành động kết quả không hợp lệ',
  RETURN_UNIT_NOT_SOLD: 'Đơn vị sản phẩm không ở trạng thái đã bán',
  RETURN_EXPORT_NOT_BELONG_TO_CUSTOMER: 'Phiếu xuất không thuộc về khách hàng đã chọn',
  RETURN_7_DAY_LIMIT: 'Chỉ được trả hàng trong vòng 7 ngày kể từ ngày xuất',
  RETURN_CONDITION_ACTION_MISMATCH: 'Tình trạng không tương thích với hành động',
  STOCK_CHECK_INVALID_SCOPE: 'Phạm vi kiểm kho không hợp lệ',
  STOCK_CHECK_NO_UNITS_IN_SCOPE: 'Không tìm thấy sản phẩm trong kho ở phạm vi đã chọn',
  STOCK_CHECK_ITEM_NOT_IN_CHECK: 'Đơn vị sản phẩm không thuộc phiếu kiểm kho này',
  STOCK_CHECK_PHOTO_REQUIRED_DAMAGED: 'Ảnh là bắt buộc khi báo cáo tình trạng HỎNG',
  STOCK_CHECK_BULK_MISSING_QTY: 'Một số mục bulk thiếu số lượng đã đếm',
  STOCK_CHECK_ADJUSTMENTS_EXIST: 'Đã tạo phiếu điều chỉnh cho phiếu kiểm kho này',

  // User
  NOT_FOUND_WITH_ID: 'Không tìm thấy người dùng',
  EMAIL_NOT_FOUND: 'Không tìm thấy tài khoản với email này',
  EMAIL_ALREADY_USED: 'Email đã được sử dụng',
  EMAIL_INVALID_FORMAT: 'Định dạng email không hợp lệ',
  EMAIL_NOT_EMPTY: 'Email không được để trống',
  USERNAME_EXISTED: 'Tên đăng nhập đã tồn tại',
  USERNAME_NOT_FOUND: 'Không tìm thấy tên đăng nhập',
  USER_EXISTED: 'Người dùng đã tồn tại',
  USER_NOT_FOUND: 'Không tìm thấy người dùng',
  USER_PASSWORD_TOO_SHORT: 'Mật khẩu phải có ít nhất 8 ký tự',
  USER_INACTIVE: 'Tài khoản đã bị khóa hoặc chưa được kích hoạt',
  USER_ALREADY_VERIFICATION: 'Tài khoản đã được xác thực',
  CANNOT_UPDATE_YOURSELF: 'Bạn không thể cập nhật tài khoản của chính mình theo cách này',
  CANNOT_CHANGE_OWN_ROLE: 'Bạn không thể thay đổi vai trò của chính mình',
  CANNOT_ASSIGN_ADMIN_ROLE: 'Không thể gán vai trò Admin qua API này',
  ROLE_NOT_FOUND: 'Không tìm thấy vai trò',

  // Handler codes
  ACCESS_DENIED: 'Từ chối truy cập',
  PERMISSION_DENIED: 'Không có quyền thực hiện thao tác này',
  RESOURCE_NOT_FOUND: 'Không tìm thấy dữ liệu',
  RESOURCE_ALREADY_EXISTED: 'Dữ liệu đã tồn tại',
  INVALID_REQUEST: 'Dữ liệu không hợp lệ',
}

export function toApiError(raw: unknown): ApiError {
  const data = (raw as { response?: { data?: ApiError } })?.response?.data
  const code: string = data?.code ?? FALLBACK_CODE
  const i18nKey = `errors.${code}`
  const message = i18n.exists(i18nKey, { lng: i18n.language })
    ? i18n.t(i18nKey)
    : (MESSAGES[code] ?? MESSAGES[FALLBACK_CODE])
  return {
    code,
    message,
    errors: data?.errors,
  }
}