package org.dawn.backend.constant.shared;

import java.text.MessageFormat;
import java.util.Locale;

public enum ErrorCode {

    // ── Auth ──────────────────────────────────────────────────────
    INVALID_PASSWORD("Invalid password"),
    INVALID_TOKEN("Invalid token"),
    TOKEN_EXPIRED("Token has expired"),
    TOKEN_INVALID_OR_EXPIRED("Token is invalid or expired"),
    TOKEN_ALREADY_USED("Token has already been used"),
    REFRESH_TOKEN_NOT_FOUND("Refresh token not found"),
    UNAUTHORIZED("Authentication required"),
    FORBIDDEN("You do not have permission to perform this action"),
    USER_NOT_AUTHENTICATED("User not authenticated"),
    INVALID_CREDENTIALS("Invalid email or password"),
    ACCOUNT_NOT_VERIFIED("Account email has not been verified"),
    ACCOUNT_NOT_ACTIVE("Account is not active"),
    REQUIRED_LOGIN("Required login"),
    OTP_RESEND_COOLDOWN("Please wait 60 seconds before requesting a new code"),
    RESET_TOKEN_INVALID("Invalid or expired reset token"),
    REFRESH_TOKEN_INVALID("Invalid or expired refresh token"),
    REFRESH_TOKEN_REUSE_DETECTED("Refresh token reuse detected"),
    REFRESH_TOKEN_EXPIRED("Refresh token has expired, please log in again"),
    TOO_MANY_LOGIN_ATTEMPTS("Too many failed login attempts, please try again later"),

    // ── Common ────────────────────────────────────────────────────
    VALIDATION_FAILED("Request validation failed"),
    ENDPOINT_NOT_FOUND("API endpoint not found"),
    INTERNAL_ERROR("An unexpected error occurred"),
    IMAGE_UPLOAD_FAILED("Image upload failed"),
    CLOUDINARY_UPLOAD_FAILED("Failed to upload file to Cloudinary"),
    CLOUDINARY_INVALID_FILE("File must be an image (jpg, png, webp) and no larger than 5MB"),
    FILE_UPLOAD_DIR_CREATE_FAILED("Could not create upload directory: {0}"),
    FILE_UPLOAD_SAVE_FAILED("Failed to save file: {0}"),
    EMAIL_SEND_FAILED("Failed to send email, please contact support"),
    METHOD_NOT_IMPLEMENTED("This feature is not yet implemented"),
    CONFLICT_DATA_CHANGED("Data was changed by another operation. Please refresh and retry."),
    CONFLICT_DUPLICATE("Duplicate data (code or serial already exists)"),
    PASSWORD_TOO_SHORT("Password must be at least 6 characters"),
    PASSWORD_NOT_MATCH("Passwords do not match"),
    INVALID_STATE_TRANSITION("Invalid transition: {0} -> {1}"),

    // ── Catalog ───────────────────────────────────────────────────
    BRAND_NOT_FOUND("Brand not found"),
    BRAND_NAME_EXISTS("Brand name already exists"),
    BRAND_NAME_REQUIRED("Brand name is required"),
    CATEGORY_NOT_FOUND("Category not found"),
    CATEGORY_NAME_REQUIRED("Category name is required"),
    CATEGORY_NAME_EXISTS("Category name already exists"),
    SUPPLIER_NOT_FOUND("Supplier not found"),
    SUPPLIER_NAME_REQUIRED("Supplier name is required"),
    SUPPLIER_NAME_EXISTS("Supplier name already exists"),
    PRODUCT_NOT_FOUND("Product not found"),
    PRODUCT_NAME_REQUIRED("Product name is required"),
    SKU_REQUIRED("SKU is required"),
    SKU_ALREADY_EXISTS("SKU already exists"),
    PRODUCT_SUPPLIERS_REQUIRED("At least one supplier is required"),
    PRODUCT_NOT_FROM_SUPPLIER("Product {0} is not supplied by the selected supplier"),
    INVALID_UNIT("Unit {0} is not a valid unit of measure"),
    TRACKING_CHANGE_BLOCKED("Cannot change tracking type while product still has stock"),
    NEGATIVE_PRICE("Sell price cannot be negative"),
    NEGATIVE_MIN_STOCK("Minimum stock cannot be negative"),
    IMAGE_LIMIT_REACHED("Product can have at most {0} images"),
    IMAGE_NOT_FOUND("Image not found"),
    INVALID_UNIT_TRACKING("Product unit {0} requires tracking_type = {1}"),

    // ── Inventory ─────────────────────────────────────────────────
    LOCATION_NOT_FOUND("Location not found"),
    LOCATION_CODE_EXISTS("Location code already exists"),
    LOCATION_CODE_REQUIRED("Zone code, shelf code, and bin code are required"),
    LOCATION_CAPACITY_EXCEEDED("Bin {0} is full ({1}/{2})"),
    LOCATION_INACTIVE("Bin {0} is deactivated and cannot receive stock"),
    LOCATION_CAPACITY_BELOW_USAGE("Bin {0} currently holds {1}, cannot reduce capacity below that"),
    CANNOT_DELETE_LOCATION_WITH_UNITS("Cannot delete location with {0} product unit(s)"),
    SOURCE_BIN_EMPTY("Source bin has no product units to relocate"),
    RELOCATE_SAME_BIN("Cannot relocate to the same bin"),
    INVALID_QUANTITY("Invalid quantity: {0}"),
    CUSTOMER_NOT_FOUND("Customer not found"),
    CUSTOMER_PHONE_EXISTS("Phone number is already used by another customer"),
    CUSTOMER_EMAIL_EXISTS("Email is already used by another customer"),
    CUSTOMER_INACTIVE("Customer is deactivated and cannot be used for new exports"),
    IMPORT_RECEIPT_NOT_FOUND("Import receipt not found"),
    IMPORT_ITEM_NOT_FOUND("Import receipt item not found"),
    IMPORT_ITEM_NOT_IN_RECEIPT("Import receipt item {0} does not belong to this receipt"),
    IMPORT_CONFIRM_ITEMS_INCOMPLETE("Confirmation must cover all receipt items; missing item(s): {0}"),
    IMPORT_LOCATION_REQUIRED("Location is required for import item {0}"),
    RECEIPT_CODE_EXISTS("Receipt code already exists"),
    PRODUCT_UNIT_NOT_FOUND("Product unit not found"),
    SERIAL_ALREADY_EXISTS("Serial number already exists"),
    SERIAL_ALREADY_EXISTS_LIST("Serial already exists: {0}"),
    SERIAL_COUNT_MUST_MATCH("Serial count must match quantity"),
    SERIAL_BLANK("Serial number cannot be blank"),
    IMPORT_ALREADY_COMPLETED("Import receipt already completed"),
    IMPORT_ALREADY_CANCELLED("Import receipt already cancelled"),
    IMPORT_CANNOT_CANCEL_UNITS_EXPORTED("Cannot cancel: some units have been exported"),
    IMPORT_CANNOT_CANCEL_UNITS_IN_SEALED_BOX("Cannot cancel: unit {0} is inside a sealed box"),
    IMPORT_CANNOT_CANCEL_UNITS_IN_STOCK_CHECK("Cannot cancel: unit {0} is in an active stock check"),
    CREATOR_CANNOT_APPROVE("Creator cannot approve their own transaction"),
    SERIAL_REQUIRED_FOR_SERIALIZED("Serial number is required for serialized products"),
    SERIAL_NOT_ALLOWED_FOR_BULK("Serial number not allowed for bulk products"),
    EXPORT_RECEIPT_NOT_FOUND("Export receipt not found"),
    EXPORT_ALREADY_CANCELLED("Export receipt already cancelled"),
    INSUFFICIENT_STOCK("Insufficient stock for {0}: available {1}, needed {2}"),
    AT_LEAST_ONE_ITEM_REQUIRED("At least one item is required"),
    EXPORT_REASON_REQUIRED("Export reason is required"),
    EXPORT_SUPPLIER_REQUIRED("Supplier is required for return-to-supplier / warranty exports"),
    CUSTOMER_REQUIRED_FOR_SALE("Customer is required for sale export"),
    INVALID_EXPORT_REASON("Invalid export reason: {0}"),
    DISPOSE_ONLY_DAMAGED("Only damaged units can be disposed"),
    BULK_CANNOT_SELECT_UNITS("Cannot select specific units for bulk products"),
    UNIT_NOT_BELONG_TO_PRODUCT("Product unit does not belong to the specified product"),
    UNIT_NOT_AVAILABLE("Product unit is not available for export"),
    SUPPLIER_REQUIRED("Supplier is required"),
    ONLY_PENDING_APPROVAL_CAN_APPROVE("Only pending approval receipts can be approved"),
    ONLY_PENDING_APPROVAL_CAN_CANCEL("Only pending approval receipts can be cancelled"),
    ONLY_DRAFT_CAN_CONFIRM("Only draft import receipts can be confirmed"),
    STOCK_CHECK_NOT_FOUND("Stock check not found"),
    STOCK_CHECK_ALREADY_APPROVED("Stock check already approved"),
    STOCK_CHECK_ALREADY_REJECTED("Stock check already rejected"),
    STOCK_CHECK_ALREADY_COMPLETED("Stock check already completed"),
    STOCK_CHECK_ITEMS_REQUIRED("At least one stock check item is required"),
    STOCK_CHECK_MUST_BE_IN_PROGRESS("Stock check must be in progress to record items"),
    STOCK_CHECK_ALREADY_STARTED("Stock check has already been started"),
    ONLY_COMPLETED_CAN_APPROVE("Only completed stock checks can be approved"),
    ONLY_COMPLETED_CAN_REJECT("Only completed stock checks can be rejected"),
    ADJUSTMENT_NOT_FOUND("Stock adjustment not found"),
    ADJUSTMENT_TYPE_REQUIRED("Adjustment type is required"),
    INVALID_ADJUSTMENT_TYPE("Invalid adjustment type: {0}"),
    ADJUSTMENT_REASON_REQUIRED("Reason is required for adjustment"),
    ADJUSTMENT_UNIT_REQUIRED("Product unit is required for {0} adjustment"),
    ADJUSTMENT_PRODUCT_REQUIRED("Product is required for found adjustment without serial"),
    ADJUSTMENT_ALREADY_APPROVED("Adjustment already approved"),
    ADJUSTMENT_ALREADY_REJECTED("Adjustment already rejected"),
    ONLY_PENDING_CAN_APPROVE("Only pending adjustments can be approved"),
    ONLY_PENDING_CAN_REJECT("Only pending adjustments can be rejected"),
    ADJUSTMENT_UNIT_NOT_RESTORABLE("Product unit is in status {0} and cannot be restored via found adjustment"),
    ADJUSTMENT_QC_ZONE_RESTORE_NOT_ALLOWED("Product unit is in QC processing zone and cannot be restored to IN_STOCK via adjustment"),
    ADJUSTMENT_UNIT_NOT_ADJUSTABLE("Product unit is in status {0} and cannot be adjusted as {1}"),
    ADJUSTMENT_UNIT_IN_SEALED_BOX("Product unit {0} is inside a sealed box and cannot be adjusted manually"),
    ADJUSTMENT_QC_ZONE_ADJUST_NOT_ALLOWED("Product unit {0} is in QC processing zone and cannot be adjusted manually"),
    ADJUSTMENT_PENDING_EXISTS("There is already a pending adjustment for product unit {0}"),
    ADJUSTMENT_SERIAL_DUPLICATE("Serial number {0} already exists"),
    ADJUSTMENT_UNIT_IN_STOCK_CHECK("Product unit {0} is part of an in-progress stock check and cannot be adjusted"),
    ADJUSTMENT_NO_EFFECT("Adjustment has no effect: product unit {0} is already in stock"),
    QC_PASS_UNIT_NOT_PASSABLE("Product unit is in status {0} and cannot be QC-passed"),
    QC_PASS_UNITS_REQUIRED("At least one product unit id is required"),
    QC_PASS_NO_SELLABLE_LOCATION("No active non-QC location with free capacity to place the QC-passed unit"),
    DISPOSE_CONFIRM_UNIT_NOT_PENDING("Product unit is in status {0} and cannot be disposed with action {1}"),
    DISPOSE_CONFIRM_UNITS_REQUIRED("At least one product unit id is required"),
    ADJUSTMENT_PHOTO_REQUIRED_DAMAGED("Photo is required for DAMAGED adjustment"),
    ADJUSTMENT_SERIAL_REQUIRED_FOUND("Serial number is required for FOUND adjustment"),
    ADJUSTMENT_LOCATION_REQUIRED_FOUND("Location is required for FOUND adjustment"),
    REJECTION_REASON_REQUIRED("Rejection reason is required"),
    PO_NOT_FOUND("Purchase order not found"),
    PO_CODE_EXISTS("Purchase order code already exists"),
    PO_ALREADY_CANCELLED("Purchase order already cancelled"),
    PO_HAS_COMPLETED_RECEIPTS("Cannot cancel purchase order that has import receipts (completed or in progress)"),
    PO_REQUIRED("Purchase order is required"),
    PO_ALREADY_IMPORTED("This purchase order already has an import receipt"),
    PO_SUPPLIER_MISMATCH("Supplier on the receipt does not match the purchase order supplier"),
    EXPORT_ITEM_NOT_FOUND("Export item not found: {0}"),
    EXPORT_ACTUAL_QTY_REQUIRED_BULK("Actual quantity required for bulk item"),
    EXPORT_QUANTITY_MISMATCH("Fulfilled quantity {0} does not match receipt quantity {1} for {2}"),
    EXPORT_SERIALS_REQUIRED("Serial numbers required for serialized item"),
    EXPORT_SERIAL_WRONG_PRODUCT("Serial {0} does not belong to product {1}"),
    EXPORT_SERIAL_NOT_AVAILABLE("Serial {0} is not available (status: {1})"),
    EXPORT_SERIAL_IN_STOCK_CHECK("Serial {0} is currently being stock-checked"),
    PRICE_ADJ_NOT_FOUND("Price adjustment not found"),
    PRICE_ADJ_ITEM_REQUIRED("Import receipt item is required"),
    PRICE_ADJ_NEW_PRICE_NEGATIVE("New price must be a non-negative value"),
    PRICE_ADJ_WHOLE_NUMBER("New price must be a whole number (no decimals)"),
    PRICE_ADJ_SAME_PRICE("New price is the same as the current price"),
    PRICE_ADJ_REASON_REQUIRED("Reason is required for price adjustment"),
    PRICE_ADJ_ONLY_PENDING_APPROVE("Only pending price adjustments can be approved"),
    PRICE_ADJ_ONLY_PENDING_REJECT("Only pending price adjustments can be rejected"),
    PRICE_ADJ_DUPLICATE_PENDING("Another pending price adjustment ({0}) already exists for this item"),
    PRICE_ADJ_REJECT_REASON_REQUIRED("Reason is required when rejecting a price adjustment"),
    PRICE_ADJ_PRICE_CHANGED("Product price has changed since the adjustment was created, please verify"),
    PRICE_ADJ_RECEIPT_NOT_COMPLETED("Cannot adjust price: import receipt is not completed yet"),
    PRICE_ADJ_ONLY_PENDING_CANCEL("Only pending price adjustments can be cancelled"),
    RETURN_RECEIPT_NOT_FOUND("Return receipt not found"),
    RETURN_RECEIPT_CODE_EXISTS("Return receipt code already exists"),
    RETURN_REASON_REQUIRED("Return reason is required"),
    RETURN_ITEMS_REQUIRED("At least one return item is required"),
    RETURN_EXPORT_REQUIRED("Original export receipt is required"),
    RETURN_ALREADY_CANCELLED("Return receipt already cancelled"),
    RETURN_ALREADY_COMPLETED("Return receipt already completed"),
    RETURN_ONLY_PENDING("Only pending return receipts can be processed"),
    RETURN_CUSTOMER_REQUIRED("Customer is required"),
    RETURN_INVALID_REASON("Invalid return reason: {0}"),
    RETURN_INVALID_CONDITION("Invalid return condition: {0}"),
    RETURN_INVALID_ACTION("Invalid resulting action: {0}"),
    RETURN_UNIT_NOT_SOLD("Product unit is not in sold state (current: {0})"),
    RETURN_UNIT_ALREADY_RETURNED("Product unit is already in another return receipt"),
    RETURN_EVIDENCE_REQUIRED("Description and photo are required for defective returns"),
    RETURN_EXPORT_NOT_BELONG_TO_CUSTOMER("Export receipt does not belong to the selected customer"),
    RETURN_7_DAY_LIMIT("Returns are only allowed within 7 days from the export date"),
    RETURN_CONDITION_ACTION_MISMATCH("Status {0} is not compatible with action {1}"),
    STOCK_CHECK_INVALID_SCOPE("Invalid scope type. Must be ZONE or CATEGORY"),
    STOCK_CHECK_NO_UNITS_IN_SCOPE("No in-stock units found in the selected scope"),
    STOCK_CHECK_ITEM_NOT_IN_CHECK("Product unit {0} is not part of this stock check"),
    STOCK_CHECK_PHOTO_REQUIRED_DAMAGED("Photo is required when reporting DAMAGED status"),
    STOCK_CHECK_BULK_MISSING_QTY("Cannot complete: {0} bulk item(s) missing counted quantity: {1}"),
    STOCK_CHECK_ADJUSTMENTS_EXIST("Adjustments already created for this stock check"),
    STOCK_CHECK_CANNOT_CANCEL_OTHERS("Only the creator can cancel a stock check"),
    STOCK_CHECK_BOX_NOT_CONFIRMED("Cannot complete: sealed box(es) not confirmed: {0}"),
    STOCK_CHECK_BOX_NOT_IN_SCOPE("Box {0} is not a sealed box in this stock check scope"),
    STOCK_CHECK_INVALID_STATUS("Invalid actual status: {0}"),
    STOCK_CHECK_UNIT_IN_ANOTHER_CHECK("Product unit {0} is already part of another in-progress stock check"),
    STOCK_CHECK_BOX_SEALED("Box {0} is sealed, unseal it before starting a stock check on it"),
    STOCK_CHECK_NOT_COMPLETED("Only a completed or expired stock check can be reopened"),
    STOCK_CHECK_HAS_APPROVED_ADJUSTMENTS("Cannot reopen: this stock check has approved adjustments"),
    BOX_NOT_FOUND("Box not found"),
    BOX_UNITS_REQUIRED("At least one product unit is required to seal a box"),
    BOX_LOCATION_REQUIRED("Location is required"),
    BOX_UNIT_ALREADY_IN_BOX("Product unit {0} is already in another box"),
    BOX_UNIT_NOT_IN_STOCK("Product unit {0} is not in stock"),
    BOX_UNSEAL_ALREADY("Box is not sealed"),
    BOX_MOVE_OPEN("Only a sealed box can be moved"),
    BOX_DELETE_SEALED("Only an unsealed box can be deleted"),
    BOX_UNIT_QTY_EXCEEDS("Quantity {0} for unit {1} exceeds its remaining quantity {2}"),
    BOX_UNIT_QTY_ZERO("Quantity for unit {0} must be greater than zero"),
    BOX_UNIT_IN_STOCK_CHECK("Product unit {0} is part of an in-progress stock check, finish it first"),
    BOX_UNIT_NO_IMPORT("Product unit {0} has no import receipt source"),
    BOX_UNIT_MIXED_IMPORT("All units in a box must come from the same import receipt"),
    BOX_MAX_UNITS("Box of type {0} can hold at most {1} units"),
    EXPORT_SERIAL_IN_BOX("Serial {0} is inside a sealed box, unseal it first"),
    EXPORT_NOT_ENOUGH_LOOSE("Not enough loose stock: {0} remaining in {1}. Unseal the box(es) before exporting"),

    // ── User ──────────────────────────────────────────────────────
    NOT_FOUND_WITH_ID("User not found: {0}"),
    EMAIL_NOT_FOUND("No account found with this email"),
    EMAIL_ALREADY_USED("Email is already in use"),
    EMAIL_INVALID_FORMAT("Invalid email format"),
    EMAIL_NOT_EMPTY("Email cannot be empty"),
    USERNAME_EXISTED("Username already exists"),
    WARRANTY_BULK_NOT_ALLOWED("Bulk products cannot be sent for warranty"),
    WARRANTY_IMPORT_ALREADY_RECEIVED("This export has already been imported back"),
    QC_STAGING_LOCATION_MISSING("QC staging location {0} is not configured in the warehouse map"),
    WARRANTY_INVALID_RESULT("Invalid warranty result type: {0}"),
    WARRANTY_IMPORT_EXPORT_NOT_REPLACEMENT("Original export is not a warranty-replacement export"),
    WARRANTY_IMPORT_SERIAL_NOT_IN_EXPORT("Serial {0} is not in the original warranty export"),
    WARRANTY_IMPORT_UNIT_NOT_SENT("Unit {0} is not in sent-to-manufacturer status"),
    WARRANTY_IMPORT_SOURCE_SERIALS_REQUIRED("Replacement serials must reference source serials from the warranty export"),
    USERNAME_NOT_FOUND("Username not found"),
    USER_EXISTED("User already exists"),
    USER_NOT_FOUND("User not found"),
    USER_PASSWORD_TOO_SHORT("Password must be at least 8 characters"),
    USER_INACTIVE("Account is locked or not yet activated"),
    USER_ALREADY_VERIFICATION("Account has already been verified"),
    CANNOT_UPDATE_YOURSELF("You cannot update your own account this way"),
    CANNOT_CHANGE_OWN_ROLE("You cannot change your own role"),
    CANNOT_ASSIGN_ADMIN_ROLE("Admin role cannot be assigned via this API"),
    ROLE_NOT_FOUND("Role not found");

    private final String template;

    ErrorCode(String template) {
        this.template = template;
    }

    public String code() {
        return name();
    }

    public String format(Object... args) {
        return MessageFormat.format(template, args);
    }
}